/**
 * Postavy žolíků (portréty z dílů, src/ui/art/figureKit.ts): základní popis každé postavy a úpravy z dávek
 * src/ui/art/jokers/*.ts (`FIGURE_PATCHES`, sloučí se přes základ). Klíč scény je `fig-<id žolíka>`.
 * Vlastní dílo (Karban, 2026).
 */
import type { FigureSpec } from './figureKit';
import { figure } from './figureKit';
import { FIGURE_PATCHES } from './jokers';
import type { SceneOp } from './sceneKit';

/** Postavy žolíků (klíč scény `fig-<id žolíka>`). */
const SPECS: Readonly<Record<string, FigureSpec>> = {
  hearts_man: {
    bg: '#e9b9b0',
    motif: 'street',
    body: '#8e1b2c',
    collar: 'shirt',
    hair: 'part',
    hairColor: '#3b2a1a',
    beard: 'mustache',
    hat: 'beret',
    hatColor: '#8e1b2c',
    mood: 'smile',
    prop: { icon: 'hearts', color: '#c8463a' },
  },
  gravedigger: {
    bg: '#8a9aa8',
    motif: 'cemetery',
    body: '#4a4f62',
    collar: 'plain',
    hair: 'short',
    hairColor: '#2f2a26',
    hat: 'flatcap',
    hatColor: '#3a3f4a',
    mood: 'flat',
    beard: 'goatee',
    prop: { icon: 'old-lantern', color: '#e6b347', size: 66 },
  },
  jeweler: {
    bg: '#d9c9e6',
    motif: 'shop',
    body: '#2f3542',
    collar: 'bow',
    accent: '#7b4fb0',
    hair: 'bald',
    hairColor: '#8a7a6a',
    glasses: true,
    mood: 'sly',
    prop: { icon: 'diamonds', color: '#5fb8d6' },
  },
  crusader: {
    bg: '#cfd8e0',
    motif: 'church',
    body: '#f4ecd8',
    collar: 'plain',
    hair: 'short',
    hairColor: '#8a5a34',
    beard: 'beard',
    mood: 'flat',
    extra: [
      [
        'f',
        '#c8463a',
        'M118,226 L132,226 L132,244 L150,244 L150,256 L132,256 L132,284 L118,284 L118,256 L100,256 L100,244 L118,244 Z',
        1.4,
      ],
    ],
    prop: { icon: 'broadsword', color: '#8d97a5', size: 72 },
  },
  early_bird: {
    bg: '#f4d9a8',
    motif: 'field',
    body: '#5f9a46',
    collar: 'shirt',
    hair: 'short',
    hairColor: '#c9a060',
    hat: 'straw',
    hatColor: '#e4c46a',
    mood: 'grin',
    prop: { icon: 'rooster', color: '#c8463a', size: 70 },
  },
  night_shift: {
    bg: '#3e4a6a',
    motif: 'night',
    body: '#3d6ab0',
    collar: 'uniform',
    accent: '#e6b347',
    hair: 'short',
    hairColor: '#2f2a26',
    hat: 'cap',
    hatColor: '#2f3e5a',
    hatAccent: '#e6b347',
    mood: 'sad',
    prop: { icon: 'alarm-clock', color: '#e6b347' },
  },
  meteorologist: {
    bg: '#b8c6d4',
    motif: 'rain',
    body: '#3d4a66',
    collar: 'tie',
    accent: '#e6b347',
    hair: 'part',
    hairColor: '#5e3a20',
    glasses: true,
    mood: 'smile',
    prop: { icon: 'umbrella', color: '#c8463a', size: 70 },
  },
  pe_teacher: {
    bg: '#c9dbe0',
    motif: 'gym',
    body: '#c8463a',
    collar: 'turtle',
    hair: 'short',
    hairColor: '#3b2a1a',
    hat: 'band',
    hatColor: '#fffaf0',
    beard: 'mustache',
    mood: 'o',
    prop: { icon: 'stopwatch', color: '#e6b347' },
  },
  party_for_two: {
    bg: '#e6c6d8',
    motif: 'pub',
    body: '#7b4fb0',
    collar: 'shirt',
    female: true,
    hair: 'long',
    hairColor: '#c9a060',
    mood: 'smile',
    prop: { icon: 'wine-glass', color: '#c8463a' },
  },
  piggy_bank: {
    bg: '#f2d0d6',
    motif: 'shop',
    body: '#5e7fb0',
    collar: 'shirt',
    hair: 'curly',
    hairColor: '#8a5a34',
    mood: 'grin',
    prop: { icon: 'piggy-bank', color: '#e8a0b0', size: 70 },
  },
  flea_trader: {
    bg: '#e0d0b0',
    motif: 'fair',
    body: '#8a6a4a',
    collar: 'vest',
    accent: '#4a5a3a',
    hair: 'bald',
    hairColor: '#5e3a20',
    beard: 'walrus',
    beardColor: '#5e3a20',
    mood: 'sly',
    prop: { icon: 'coins-pile', color: '#e6b347' },
  },
  helpline_aunt: {
    bg: '#e8d8f0',
    motif: 'office',
    body: '#c86a8a',
    collar: 'plain',
    female: true,
    hair: 'curly',
    hairColor: '#b0b0b0',
    glasses: true,
    mood: 'smile',
    prop: { icon: 'rotary-phone', color: '#2f3542' },
  },
  weekend_cottager: {
    bg: '#c9dbc0',
    motif: 'cabin',
    body: '#3f7334',
    collar: 'shirt',
    hair: 'short',
    hairColor: '#5e3a20',
    hat: 'bucket',
    hatColor: '#d8c7a6',
    beard: 'beard',
    beardColor: '#6b4423',
    mood: 'grin',
    prop: { icon: 'battle-axe', color: '#8d97a5', size: 70 },
  },
  shooting_gallery: {
    bg: '#f0d8a8',
    motif: 'fair',
    body: '#3d6ab0',
    collar: 'vest',
    accent: '#c8463a',
    hair: 'part',
    hairColor: '#3b2a1a',
    mood: 'sly',
    prop: { icon: 'trophy', color: '#e6b347' },
  },
  tobacconist: {
    bg: '#e8d8b8',
    motif: 'kiosk',
    body: '#6a4a3a',
    collar: 'vest',
    accent: '#3d4a66',
    hair: 'bald',
    hairColor: '#8a7a6a',
    glasses: true,
    beard: 'mustache',
    beardColor: '#8a7a6a',
    mood: 'flat',
    prop: { icon: 'newspaper', color: '#eadfc6', size: 70 },
  },
  ticket_inspector: {
    bg: '#d0d8c8',
    motif: 'tram',
    body: '#2f3e5a',
    collar: 'uniform',
    accent: '#e6b347',
    hair: 'short',
    hairColor: '#2f2a26',
    hat: 'cap',
    hatColor: '#2f3e5a',
    hatAccent: '#e6b347',
    beard: 'mustache',
    beardColor: '#2f2a26',
    mood: 'sly',
    prop: { icon: 'ticket', color: '#e6b347' },
  },
  doorman: {
    bg: '#d8ccb8',
    motif: 'office',
    body: '#4a5a3a',
    collar: 'uniform',
    accent: '#e6b347',
    hair: 'bald',
    hairColor: '#b0b0b0',
    hat: 'cap',
    hatColor: '#4a5a3a',
    hatAccent: '#e6b347',
    beard: 'walrus',
    beardColor: '#b0b0b0',
    mood: 'flat',
    prop: { icon: 'key', color: '#e6b347' },
  },
  goldsmith: {
    bg: '#f0e0b0',
    motif: 'workshop',
    body: '#6a4a3a',
    collar: 'apron',
    hair: 'short',
    hairColor: '#5e3a20',
    glasses: true,
    beard: 'beard',
    beardColor: '#5e3a20',
    mood: 'smile',
    prop: { icon: 'gold-bar', color: '#e6b347' },
  },
  paver: {
    bg: '#d8d0c0',
    motif: 'street',
    body: '#5e7fb0',
    collar: 'vestHi',
    hair: 'short',
    hairColor: '#3b2a1a',
    hat: 'hard',
    hatColor: '#e6b347',
    beard: 'mustache',
    beardColor: '#3b2a1a',
    mood: 'flat',
    prop: { icon: 'warhammer', color: '#8d97a5', size: 70 },
  },
  postman: {
    bg: '#e6d8b0',
    motif: 'street',
    body: '#3d6ab0',
    collar: 'uniform',
    accent: '#e6b347',
    hair: 'short',
    hairColor: '#8a5a34',
    hat: 'cap',
    hatColor: '#3d6ab0',
    hatAccent: '#e6b347',
    mood: 'grin',
    prop: { icon: 'present', color: '#d9a050' },
  },
  grocer: {
    bg: '#dcd8b0',
    motif: 'shop',
    body: '#5f9a46',
    collar: 'apron',
    hair: 'bald',
    hairColor: '#5e3a20',
    beard: 'walrus',
    beardColor: '#5e3a20',
    mood: 'smile',
    redNose: true,
    prop: { icon: 'potato', color: '#c9a060' },
  },
  grill_dad: {
    bg: '#c9dbc0',
    motif: 'cabin',
    body: '#c8463a',
    collar: 'apron',
    hair: 'bald',
    hairColor: '#6b4423',
    beard: 'mustache',
    beardColor: '#6b4423',
    mood: 'grin',
    redNose: true,
    prop: { icon: 'roast-chicken', color: '#d9a050', size: 70 },
  },
  teacher: {
    bg: '#d8e0d0',
    motif: 'classroom',
    body: '#7b4fb0',
    collar: 'plain',
    female: true,
    hair: 'bun',
    hairColor: '#5e3a20',
    glasses: true,
    mood: 'flat',
    prop: { icon: 'open-book', color: '#eadfc6', size: 70 },
  },
  tram_driver: {
    bg: '#d8d0c0',
    motif: 'tram',
    body: '#3d4a66',
    collar: 'uniform',
    accent: '#c8463a',
    hair: 'short',
    hairColor: '#3b2a1a',
    hat: 'cap',
    hatColor: '#c8463a',
    hatAccent: '#e6b347',
    mood: 'smile',
    prop: { icon: 'ringing-bell', color: '#e6b347' },
  },
  punter: {
    bg: '#cfe0c8',
    motif: 'pub',
    body: '#6a5a4a',
    collar: 'shirt',
    hair: 'part',
    hairColor: '#2f2a26',
    hat: 'flatcap',
    hatColor: '#6a5a4a',
    mood: 'sly',
    redNose: true,
    prop: { icon: 'coinflip', color: '#e6b347' },
  },
  pavlac_gossip: {
    bg: '#e8dcc8',
    motif: 'street',
    body: '#5e7fb0',
    collar: 'plain',
    female: true,
    hair: 'none',
    hat: 'scarf',
    hatColor: '#c8463a',
    mood: 'o',
    prop: { icon: 'eyeball', color: '#fffaf0', size: 58 },
  },
  temp_worker: {
    bg: '#f0dca8',
    motif: 'field',
    body: '#5e7fb0',
    collar: 'turtle',
    hair: 'curly',
    hairColor: '#c9a060',
    hat: 'cap',
    hatColor: '#c8463a',
    hatAccent: '#fffaf0',
    mood: 'smile',
    prop: { icon: 'wheat', color: '#e4c46a', size: 70 },
  },
  fisherman: {
    bg: '#b8cfd8',
    motif: 'river',
    body: '#4a5a3a',
    collar: 'turtle',
    hair: 'short',
    hairColor: '#6b4423',
    hat: 'bucket',
    hatColor: '#6a8a4a',
    beard: 'beard',
    beardColor: '#8a7a6a',
    mood: 'smile',
    prop: { icon: 'tropical-fish', color: '#6f9fc0', size: 70 },
  },
  garbage_man: {
    bg: '#d0d8c8',
    motif: 'street',
    body: '#5e7fb0',
    collar: 'vestHi',
    hair: 'short',
    hairColor: '#2f2a26',
    hat: 'cap',
    hatColor: '#f0a040',
    hatAccent: '#fffaf0',
    mood: 'grin',
    prop: { icon: 'broken-bottle', color: '#5f9a46', size: 64 },
  },
  pig_slaughter: {
    bg: '#f0d8d0',
    motif: 'kitchen',
    body: '#fffaf0',
    collar: 'apron',
    hair: 'short',
    hairColor: '#3b2a1a',
    hat: 'chef',
    beard: 'walrus',
    beardColor: '#3b2a1a',
    mood: 'grin',
    redNose: true,
    prop: { icon: 'sausage', color: '#c8463a' },
  },
  mushroom_picker: {
    bg: '#cfdcc0',
    motif: 'forest',
    body: '#8a6a4a',
    collar: 'turtle',
    female: true,
    hair: 'none',
    hat: 'scarf',
    hatColor: '#3d6ab0',
    mood: 'grin',
    prop: { icon: 'mushroom', color: '#b5653f', size: 66 },
  },
  herbalist: {
    bg: '#d8e0c0',
    motif: 'forest',
    body: '#6a5a3a',
    collar: 'plain',
    female: true,
    hair: 'none',
    hat: 'scarf',
    hatColor: '#5f9a46',
    mood: 'sly',
    prop: { icon: 'garlic', color: '#eadfc6' },
  },
  regular: {
    bg: '#d8c09a',
    motif: 'pub',
    body: '#5e7fb0',
    collar: 'shirt',
    hair: 'bald',
    hairColor: '#8a7a6a',
    hat: 'flatcap',
    hatColor: '#6d8f5a',
    beard: 'walrus',
    beardColor: '#6b4423',
    mood: 'smile',
    redNose: true,
    prop: { icon: 'beer-stein', color: '#e6b347', size: 70 },
  },
  beer_sommelier: {
    bg: '#e0c890',
    motif: 'pub',
    body: '#2f3542',
    collar: 'bow',
    accent: '#c8463a',
    hair: 'part',
    hairColor: '#8a7a6a',
    beard: 'goatee',
    beardColor: '#8a7a6a',
    mood: 'sly',
    prop: { icon: 'beer-bottle', color: '#5f9a46' },
  },
  archivist: {
    bg: '#d8ccb0',
    motif: 'office',
    body: '#6a5a4a',
    collar: 'turtle',
    hair: 'bald',
    hairColor: '#b0b0b0',
    glasses: true,
    beard: 'beard',
    beardColor: '#b0b0b0',
    mood: 'flat',
    prop: { icon: 'papers', color: '#eadfc6' },
  },
  fair_magician: {
    bg: '#d8c0e0',
    motif: 'fair',
    body: '#2f3542',
    collar: 'bow',
    accent: '#e6b347',
    hair: 'part',
    hairColor: '#2f2a26',
    hat: 'top',
    hatColor: '#2f3542',
    hatAccent: '#7b4fb0',
    beard: 'goatee',
    beardColor: '#2f2a26',
    mood: 'sly',
    prop: { icon: 'rabbit', color: '#fffaf0', size: 62 },
  },
  tour_guide: {
    bg: '#c9dbe8',
    motif: 'sky',
    body: '#e6b347',
    collar: 'shirt',
    female: true,
    hair: 'bob',
    hairColor: '#8a5a34',
    mood: 'grin',
    prop: { icon: 'umbrella', color: '#3d6ab0', size: 70 },
  },
  spa_guest: {
    bg: '#d0e0dc',
    motif: 'spa',
    body: '#eadfc6',
    collar: 'shirt',
    hair: 'bald',
    hairColor: '#b0b0b0',
    beard: 'walrus',
    beardColor: '#b0b0b0',
    hat: 'top',
    hatColor: '#3d4a66',
    hatAccent: '#e6b347',
    mood: 'smile',
    prop: { icon: 'glass-shot', color: '#fffaf0', size: 56 },
  },
  chronicler: {
    bg: '#e0d4b8',
    motif: 'office',
    body: '#4a5a3a',
    collar: 'plain',
    hair: 'part',
    hairColor: '#8a7a6a',
    hat: 'beret',
    hatColor: '#2f3542',
    glasses: true,
    mood: 'flat',
    prop: { icon: 'quill-ink', color: '#2f3542' },
  },
  glassblower: {
    bg: '#f0d8b0',
    motif: 'workshop',
    body: '#6a4a3a',
    collar: 'apron',
    hair: 'short',
    hairColor: '#3b2a1a',
    beard: 'beard',
    beardColor: '#3b2a1a',
    mood: 'o',
    prop: { icon: 'wine-bottle', color: '#5fb8d6' },
  },
  notary_public: {
    bg: '#d8d0c8',
    motif: 'office',
    body: '#2f3542',
    collar: 'tie',
    accent: '#8e1b2c',
    hair: 'part',
    hairColor: '#b0b0b0',
    glasses: true,
    mood: 'flat',
    prop: { icon: 'scroll-unfurled', color: '#eadfc6', size: 70 },
  },
  witch: {
    bg: '#b8a8c8',
    motif: 'night',
    body: '#3d3a4a',
    collar: 'plain',
    female: true,
    hair: 'long',
    hairColor: '#8a8a8a',
    hat: 'witch',
    hatColor: '#2f2a3a',
    hatAccent: '#7b4fb0',
    mood: 'sly',
    skin: '#d8c9a8',
    prop: { icon: 'cat', color: '#3d3a4a', size: 66 },
  },
  will_o_wisp: {
    bg: '#3a5a50',
    motif: 'marsh',
    body: '#c9dbe0',
    collar: 'plain',
    female: true,
    hair: 'long',
    hairColor: '#e4e0c0',
    mood: 'sly',
    skin: '#e8eedc',
    prop: { icon: 'lantern', color: '#ffd34d' },
  },
  noon_witch: {
    bg: '#f0dca0',
    motif: 'field',
    body: '#8a8478',
    collar: 'plain',
    female: true,
    hair: 'none',
    hat: 'scarf',
    hatColor: '#6a6a60',
    mood: 'flat',
    skin: '#d8c9a8',
    prop: { icon: 'scythe', color: '#8d97a5', size: 76 },
  },
  klekanice: {
    bg: '#2e3550',
    motif: 'night',
    body: '#e8e4dc',
    collar: 'plain',
    hair: 'none',
    hat: 'hood',
    hatColor: '#e8e4dc',
    mood: 'o',
    skin: '#c8ccd0',
    prop: { icon: 'ringing-bell', color: '#e6b347' },
  },
  parish_priest: {
    bg: '#e0d8c8',
    motif: 'church',
    body: '#2f2a2a',
    collar: 'cassock',
    hair: 'bald',
    hairColor: '#b0b0b0',
    glasses: true,
    mood: 'smile',
    redNose: true,
    prop: { icon: 'candle-light', color: '#fffaf0' },
  },
  seer: {
    bg: '#c8b0d8',
    motif: 'night',
    body: '#7b4fb0',
    collar: 'plain',
    female: true,
    hair: 'long',
    hairColor: '#2f2a26',
    hat: 'scarf',
    hatColor: '#e6b347',
    mood: 'sly',
    prop: { icon: 'crystal-ball', color: '#a8c4e8' },
  },
  court_painter: {
    bg: '#e8dcc8',
    motif: 'gallery',
    body: '#5e7fb0',
    collar: 'bow',
    accent: '#c8463a',
    hair: 'curly',
    hairColor: '#6b4423',
    hat: 'beret',
    hatColor: '#c8463a',
    beard: 'goatee',
    beardColor: '#6b4423',
    mood: 'smile',
    prop: { icon: 'sunflower', color: '#e6b347', size: 70 },
  },
  colorblind_uncle: {
    bg: '#d0e0c8',
    motif: 'street',
    body: '#c86a8a',
    collar: 'tie',
    accent: '#5f9a46',
    hair: 'bald',
    hairColor: '#8a7a6a',
    glasses: true,
    beard: 'mustache',
    beardColor: '#8a7a6a',
    mood: 'grin',
    prop: { icon: 'spectacles', color: '#3d6ab0', size: 60 },
  },
  anonymous_commenter: {
    bg: '#2e3550',
    motif: 'screen',
    body: '#4a4f62',
    collar: 'plain',
    hair: 'none',
    hat: 'hood',
    hatColor: '#5a5f72',
    mood: 'sly',
    skin: '#c8ccd0',
    prop: { icon: 'laptop', color: '#8d97a5', size: 70 },
  },
  brno_native: {
    bg: '#d8d0c0',
    motif: 'street',
    body: '#c8463a',
    collar: 'shirt',
    hair: 'short',
    hairColor: '#3b2a1a',
    hat: 'flatcap',
    hatColor: '#3d4a66',
    mood: 'grin',
    prop: { icon: 'dragon-head', color: '#5f9a46', size: 70 },
  },
  old_guard: {
    bg: '#d8d0c0',
    motif: 'pub',
    body: '#4a5a3a',
    collar: 'uniform',
    accent: '#e6b347',
    hair: 'bald',
    hairColor: '#b0b0b0',
    beard: 'walrus',
    beardColor: '#c0c0c0',
    hat: 'cap',
    hatColor: '#4a5a3a',
    hatAccent: '#e6b347',
    mood: 'flat',
    redNose: true,
    prop: { icon: 'shield', color: '#8d97a5' },
    extra: [
      ['f', '#e6b347', 'M100,232 L108,232 L108,246 L100,246 Z', 1],
      ['f', '#c8463a', 'M110,232 L118,232 L118,246 L110,246 Z', 1],
    ],
  },
  beer_belly: {
    bg: '#d8c09a',
    motif: 'pub',
    body: '#eadfc6',
    collar: 'shirt',
    hair: 'bald',
    hairColor: '#8a7a6a',
    beard: 'walrus',
    beardColor: '#6b4423',
    mood: 'grin',
    redNose: true,
    extra: [
      ['f', '#eadfc6', 'M56,290 C50,236 84,214 125,214 C166,214 200,236 194,290 Z', 2.4],
      ['l', 'M125,226 L125,284', 1],
      ['f', '#e6b347', 'M122,236 l6,0 l0,6 l-6,0 Z M122,256 l6,0 l0,6 l-6,0 Z', 0.8],
    ],
    prop: { icon: 'beer-bottle', color: '#5f9a46', x: 162, y: 194 },
  },
  office_connection: {
    bg: '#d8d4c8',
    motif: 'office',
    body: '#5e7fb0',
    collar: 'tie',
    accent: '#c8463a',
    hair: 'part',
    hairColor: '#3b2a1a',
    glasses: true,
    mood: 'sly',
    prop: { icon: 'stamper', color: '#c8463a' },
  },
  brass_band: {
    bg: '#e6d8b0',
    motif: 'street',
    body: '#3d6ab0',
    collar: 'uniform',
    accent: '#e6b347',
    hair: 'short',
    hairColor: '#5e3a20',
    hat: 'cap',
    hatColor: '#3d6ab0',
    hatAccent: '#e6b347',
    beard: 'walrus',
    beardColor: '#5e3a20',
    mood: 'o',
    redNose: true,
    prop: { icon: 'trumpet', color: '#e6b347', size: 70 },
  },
  spartakiada: {
    bg: '#d8e8f0',
    motif: 'gym',
    body: '#fffaf0',
    collar: 'turtle',
    female: true,
    hair: 'bob',
    hairColor: '#3b2a1a',
    hat: 'band',
    hatColor: '#c8463a',
    mood: 'grin',
    prop: { icon: 'round-star', color: '#e6b347' },
  },
  derby_fans: {
    bg: '#e0d0c8',
    motif: 'street',
    body: '#c8463a',
    collar: 'plain',
    hair: 'short',
    hairColor: '#2f2a26',
    hat: 'bucket',
    hatColor: '#2f2a26',
    mood: 'grin',
    prop: { icon: 'trumpet', color: '#e6b347' },
    extra: [['s', '#2f2a26', 'M98,214 C112,226 138,226 152,214', 8]],
  },
  pub_quiz: {
    bg: '#dcc8e0',
    motif: 'pub',
    body: '#7b4fb0',
    collar: 'bow',
    accent: '#e6b347',
    hair: 'curly',
    hairColor: '#6b4423',
    glasses: true,
    mood: 'grin',
    prop: { icon: 'microphone', color: '#8d97a5' },
  },
  viral_video: {
    bg: '#f0c8d8',
    motif: 'street',
    body: '#e8706a',
    collar: 'plain',
    female: true,
    hair: 'long',
    hairColor: '#e4c46a',
    mood: 'grin',
    prop: { icon: 'smartphone', color: '#2f3542' },
  },
  impersonator: {
    bg: '#d8c8b8',
    motif: 'fair',
    body: '#2f3542',
    collar: 'bow',
    accent: '#c8463a',
    hair: 'part',
    hairColor: '#2f2a26',
    beard: 'mustache',
    beardColor: '#2f2a26',
    mood: 'sly',
    prop: { icon: 'drama-masks', color: '#e6b347', size: 68 },
  },
  hejkal: {
    bg: '#b8ccb0',
    motif: 'forest',
    skin: '#a8b888',
    body: '#5a6a40',
    collar: 'plain',
    hair: 'curly',
    hairColor: '#4a5a30',
    beard: 'beard',
    beardColor: '#5a6a3a',
    mood: 'o',
    prop: { icon: 'megaphone', color: '#b07a3a' },
  },
  // ── patch 1.0.2 „Pouť a volby“ ──
  fair_photographer: {
    bg: '#d8cce8',
    motif: 'fair',
    body: '#3b2f5c',
    collar: 'vest',
    accent: '#f2c14e',
    hair: 'curly',
    hairColor: '#2f2a26',
    beard: 'mustache',
    beardColor: '#2f2a26',
    hat: 'beret',
    hatColor: '#1f1a2e',
    mood: 'grin',
    prop: { icon: 'sparkles', color: '#f2c14e', size: 70 },
  },
  recount_committee: {
    bg: '#cfdde0',
    motif: 'office',
    body: '#2f4858',
    collar: 'tie',
    accent: '#e05d5d',
    female: true,
    hair: 'bun',
    hairColor: '#7a6a5a',
    glasses: true,
    mood: 'flat',
    prop: { icon: 'quill-ink', color: '#2f3542' },
  },
  football_fan: {
    bg: '#d3e3ee',
    motif: 'stadium',
    body: '#d7442c',
    body2: '#f4ede0',
    collar: 'jersey',
    accent: '#f4ede0',
    neckScarf: { color: '#d7442c', stripe: '#f4ede0' },
    hair: 'short',
    hairColor: '#5e3a20',
    beard: 'goatee',
    beardColor: '#5e3a20',
    hat: 'cap',
    hatColor: '#d7442c',
    hatAccent: '#f4ede0',
    redNose: true,
    mood: 'o',
    prop: { icon: 'megaphone', color: '#e05d5d' },
  },
  crown_goldsmith: {
    bg: '#f3e2b8',
    motif: 'shop',
    body: '#3a2f4a',
    collar: 'bow',
    accent: '#ffd23f',
    hair: 'bald',
    hairColor: '#8a7a6a',
    beard: 'walrus',
    beardColor: '#b0a090',
    glasses: true,
    mood: 'sly',
    prop: { icon: 'crown-coin', color: '#e6b347' },
  },
  beggar: {
    bg: '#d6cfc0',
    motif: 'street',
    body: '#6a5f4c',
    collar: 'plain',
    hair: 'long',
    hairColor: '#6b6258',
    beard: 'beard',
    beardColor: '#8a8070',
    hat: 'flatcap',
    hatColor: '#4a4338',
    mood: 'sad',
    prop: { icon: 'receive-money', color: '#c9a227' },
  },
};

/** Tahy všech portrétů (klíč `fig-<id>`). */
export const FIGURES: Readonly<Record<string, readonly SceneOp[]>> = Object.fromEntries(
  Object.entries(SPECS).map(([id, spec]) => [`fig-${id}`, figure({ ...spec, ...FIGURE_PATCHES[id] })]),
);

/** Id žolíků, které mají portrét. */
export const FIGURE_IDS: readonly string[] = Object.keys(SPECS);
